#! /bin/sh

sxhkd &

# Use polybar to manage the bar
/usr/bin/polybar bar1 &
/usr/bin/polybar bar2 &

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-1 -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Follow mouse focus
bspc config focus_follows_pointer true

# Use the background photo
feh --bg-fill ~/.config/bspwm/background/background.jpg
